server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: nexus
  datasource:
    # PostgreSQL Database Configuration (default)
    # For H2 testing, use application-test.yml profile
    url: jdbc:postgresql://localhost:5432/nexus_hrms
    username: rameshbabu
    password: ${POSTGRES_PASSWORD:nexus_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: nx_core
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'validate' for production
    show-sql: true
  h2:
    console:
      enabled: false  # Disabled by default (PostgreSQL mode)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/systech

# CORS Configuration for React Frontend
nexus:
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
        - http://localhost:3001
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
        - X-Requested-With
      max-age: 3600

logging:
  level:
    com.systech.nexus: DEBUG
    root: INFO
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"