# default Profile Configuration for JWT Authentication
# Inherits base configuration from application.yml

spring:
  application:
    name: nexus
  profiles:
    active: dev
  datasource:
    # PostgreSQL Database Configuration (default)
    url: jdbc:postgresql://localhost:5432/nexus_hrms
    username: rameshbabu
    password: ${POSTGRES_PASSWORD:nexus_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: nx_core
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'validate' for production
    show-sql: true
  h2:
    console:
      enabled: false  # Disabled by default (PostgreSQL mode)
  security:
    oauth2:
      resourceserver:
        jwt:
          # For development, we'll use the Keycloak instance from podman configuration
          # This will be used when Keycloak is available
          issuer-uri: http://localhost:8090/realms/systech
          # Allow startup without Keycloak by disabling eager validation
          jwk-set-uri: http://localhost:8090/realms/systech/protocol/openid-connect/certs

# CORS Configuration for React Frontend (Development)
nexus:
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
        - http://localhost:3001
        - http://localhost:8080
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
        - X-Requested-With
      max-age: 3600

# Keycloak Admin Configuration for User Management
keycloak:
  admin:
    server-url: http://localhost:8090
    realm: systech
    client-id: admin-cli
    username: admin
    password: secret

# Development-specific logging (more verbose for security debugging)
logging:
  level:
    com.systech.nexus: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.cors: DEBUG
    root: INFO